# Generated by Django 5.1.6 on 2025-06-15 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Guruh ochilgan vaqti'),
        ),
    ]
