# Generated by Django 5.1.6 on 2025-06-23 13:16

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_profile_image_path),
        ),
    ]
