# Generated by Django 5.1.6 on 2025-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='000000000', max_length=20, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
