# Generated by Django 5.1.6 on 2025-07-01 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
