# Generated by Django 5.1.6 on 2025-07-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studentquizresult_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentquizresult',
            name='quiz_last_updated',
            field=models.DateTimeField(default='2025-07-04 21:00:00'),
            preserve_default=False,
        ),
    ]
