# Generated by Django 5.1.6 on 2025-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100, verbose_name='Maksimal ball'),
        ),
    ]
