# Generated by Django 5.1.6 on 2025-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_assignment_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
