# Generated by Django 5.1.6 on 2025-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_score',
            field=models.PositiveIntegerField(default=100, verbose_name='Maksimal ball'),
        ),
    ]
