# Generated by Django 5.1.6 on 2025-08-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_studentgroupjoin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGroupJoin',
        ),
    ]
