# Generated by Django 5.1.6 on 2025-08-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_groupstudentmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
    ]
