# Generated by Django 5.1.6 on 2025-08-02 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_group_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='student_groups', through='main.GroupStudentMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
