# Generated by Django 5.1.6 on 2025-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_group_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Umumiy rasm', max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='site_images/', verbose_name='Umumiy rasm')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Umumiy rasm sozlamasi',
                'verbose_name_plural': 'Umumiy rasm sozlamalari',
            },
        ),
    ]
