# Generated by Django 5.1.6 on 2025-08-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
