# Generated by Django 5.1.6 on 2025-08-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='global/')),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
