# Generated by Django 5.1.6 on 2025-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Rasm yuklash', 'verbose_name_plural': 'Rasm yuklash'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='defaults/', verbose_name='Foydalanuvchilar uchun default profil rasmi'),
        ),
    ]
