# Generated by Django 5.1.6 on 2025-08-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Logatip', 'verbose_name_plural': 'Logatip'},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_profile_image',
        ),
    ]
