# Generated by Django 5.1.6 on 2025-08-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='default/')),
            ],
            options={
                'verbose_name': 'Default img',
                'verbose_name_plural': 'Default img',
            },
        ),
    ]
