# Generated by Django 5.1.6 on 2025-08-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_profilesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_duration_months', models.PositiveIntegerField(default=6, verbose_name='Kurs davomiyligi (oy)')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Bir oylik to'lov summasi (so'm)")),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_setting', to='main.group')),
            ],
        ),
    ]
