# Generated by Django 5.1.6 on 2025-08-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_studentpayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpayment',
            unique_together={('student', 'group', 'month')},
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='year',
        ),
    ]
