# Generated by Django 5.1.6 on 2025-08-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_studentpayment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpayment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='student',
        ),
        migrations.DeleteModel(
            name='GroupPaymentSetting',
        ),
        migrations.DeleteModel(
            name='StudentPayment',
        ),
    ]
