# Generated by Django 5.1.6 on 2025-08-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_studentpayment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_duration_months', models.PositiveIntegerField(verbose_name='Kurs davomiyligi (oy)')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Har oy uchun to'lov summasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='main.group')),
            ],
        ),
    ]
