# Generated by Django 5.2.6 on 2026-07-04 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_studentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('correct_explanation', models.TextField(blank=True, null=True, verbose_name="To'g'ri javob izohi")),
            ],
        ),
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Javob varianti')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.aiquestion')),
            ],
        ),
        migrations.CreateModel(
            name='AIQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('categories', models.TextField(verbose_name='Tanlangan kategoriyalar')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich (Beginner / A1-A2)"), ('intermediate', "O'rta (Intermediate / B1-B2)"), ('advanced', 'Yuqori (Advanced / C1-C2)')], max_length=20, verbose_name='Daraja')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name="To'plangan ball")),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Maksimal ball')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='AI Natija Tahlili')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aiquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.aiquiz'),
        ),
        migrations.CreateModel(
            name='StudentAIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aiquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='main.aiquiz')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.aianswer')),
            ],
        ),
    ]
