# Generated by Django 5.2.6 on 2026-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_aiquestion_aianswer_aiquiz_aiquestion_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='Bajarish vaqti (daqiqa)'),
        ),
    ]
