# Generated by Django 5.2.6 on 2026-07-04 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_aiquiz_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(verbose_name='AI Achchiq Tanbehi')),
                ('plan', models.TextField(verbose_name='Kelgusi kunlar rejasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
