# Generated by Django 5.2.6 on 2026-07-08 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_studentaiplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('target_role', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('teacher', "Faqat o'qituvchilar"), ('student', "Faqat o'quvchilar")], default='all', max_length=15, verbose_name='Kimlar uchun')),
                ('category', models.CharField(choices=[('always_show', "Doimiy ko'rsatish (Banner)"), ('one_time', 'Tizimga 1-marta kirganda (Bir martalik)')], default='always_show', max_length=15, verbose_name='Turkum')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
