# Generated by Django 5.2.6 on 2026-07-09 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_systemannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=255, verbose_name='Dars mavzusi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Konspekt / Dars rejasi')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Uyga vazifa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.group')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
