# Generated by Django 5.2.6 on 2026-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
