# Generated by Django 5.2.6 on 2026-07-16 06:57

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_usersession_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Dars sarlavhasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dars tavsifi')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=main.models.video_upload_path, verbose_name='Video fayl')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube havola')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.group', verbose_name='Guruh')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
        ),
    ]
