# Generated by Django 5.2.6 on 2026-07-17 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_grouplesson_file_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTMExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Imtihon nomi')),
                ('registration_deadline', models.DateTimeField(verbose_name="Ro'yxatdan o'tish muddati")),
                ('exam_date', models.DateTimeField(verbose_name='Imtihon vaqti')),
                ('block1_questions_count', models.IntegerField(default=30, verbose_name='1-blok savollar soni')),
                ('block1_score', models.FloatField(default=3.1, verbose_name='1-blok har bir savol bali')),
                ('block2_questions_count', models.IntegerField(default=30, verbose_name='2-blok savollar soni')),
                ('block2_score', models.FloatField(default=2.1, verbose_name='2-blok har bir savol bali')),
                ('compulsory_questions_count', models.IntegerField(default=10, verbose_name='Majburiy fan har bir savol bali')),
                ('compulsory_score', models.FloatField(default=1.1, verbose_name='Majburiy fan har bir savol bali')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
        ),
        migrations.CreateModel(
            name='DTMQuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('difficulty', models.IntegerField(default=2, verbose_name="Qiyinlik darajasi (1: Qiyin, 2: O'rtacha, 3: Oson)")),
                ('is_compulsory', models.BooleanField(default=False, verbose_name='Majburiy fan savoli')),
                ('text', models.TextField(verbose_name='Savol matni')),
            ],
        ),
        migrations.CreateModel(
            name='DTMAnswerPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.dtmquestionpool')),
            ],
        ),
        migrations.CreateModel(
            name='DTMRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block1_subject', models.CharField(max_length=100, verbose_name='1-blok fani')),
                ('block2_subject', models.CharField(max_length=100, verbose_name='2-blok fani')),
                ('take_compulsory', models.BooleanField(default=True, verbose_name='Majburiy fanlarni topshiradi')),
                ('booklet_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Kitobcha raqami')),
                ('booklet_file', models.FileField(blank=True, null=True, upload_to='dtm_booklets/', verbose_name='Savollar kitobchasi PDF')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.dtmexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDTMExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_block1', models.FloatField(default=0.0, verbose_name='1-blok bali')),
                ('score_block2', models.FloatField(default=0.0, verbose_name='2-blok bali')),
                ('score_compulsory', models.FloatField(default=0.0, verbose_name='Majburiy fanlar bali')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Umumiy ball')),
                ('student_answers_raw', models.TextField(blank=True, null=True, verbose_name='Talaba javoblari')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='main.dtmregistration')),
            ],
        ),
    ]
