# Generated by Django 5.2.6 on 2026-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_dtmexam_dtmquestionpool_dtmanswerpool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmregistration',
            name='booklet_answers_key',
            field=models.TextField(blank=True, null=True, verbose_name='Kitobcha javoblari kaliti'),
        ),
    ]
