# Generated by Django 5.2.6 on 2026-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_dtmregistration_booklet_answers_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Logatip va Sozlamalar', 'verbose_name_plural': 'Logatip va Sozlamalar'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='FUMA ISAK', max_length=255, verbose_name='Brend nomi / Sayt nomi'),
        ),
    ]
