# Generated by Django 5.2.6 on 2026-07-18 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_subject_group_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Material nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='subject_materials/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.subject', verbose_name='Fan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklovchi')),
            ],
            options={
                'verbose_name': 'Fan materiali',
                'verbose_name_plural': 'Fan materiallari',
            },
        ),
    ]
