# Generated by Django 5.2.6 on 2026-07-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_subjectmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='main.subject', verbose_name='Dars beradigan fanlari'),
        ),
    ]
