# Generated by Django 5.2.6 on 2026-07-26 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_customuser_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='aiquiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aiquiz',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='aiquiz',
            name='level',
            field=models.CharField(choices=[('beginner', "Boshlang'ich (Beginner / A1-A2)"), ('intermediate', "O'rta (Intermediate / B1-B2)"), ('advanced', 'Yuqori (Advanced / C1-C2)')], db_index=True, max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='To‘g‘ri javobmi?'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(db_index=True, verbose_name='Topshiriq muddati'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmadi')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Harakat turi'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='dtmanswerpool',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='dtmexam',
            name='exam_date',
            field=models.DateTimeField(db_index=True, verbose_name='Imtihon vaqti'),
        ),
        migrations.AlterField(
            model_name='dtmexam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='dtmexam',
            name='registration_deadline',
            field=models.DateTimeField(db_index=True, verbose_name="Ro'yxatdan o'tish muddati"),
        ),
        migrations.AlterField(
            model_name='dtmquestionpool',
            name='difficulty',
            field=models.IntegerField(db_index=True, default=2, verbose_name="Qiyinlik darajasi (1: Qiyin, 2: O'rtacha, 3: Oson)"),
        ),
        migrations.AlterField(
            model_name='dtmquestionpool',
            name='is_compulsory',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Majburiy fan savoli'),
        ),
        migrations.AlterField(
            model_name='dtmquestionpool',
            name='subject',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='dtmregistration',
            name='block1_subject',
            field=models.CharField(db_index=True, max_length=100, verbose_name='1-blok fani'),
        ),
        migrations.AlterField(
            model_name='dtmregistration',
            name='block2_subject',
            field=models.CharField(db_index=True, max_length=100, verbose_name='2-blok fani'),
        ),
        migrations.AlterField(
            model_name='dtmregistration',
            name='booklet_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Kitobcha raqami'),
        ),
        migrations.AlterField(
            model_name='dtmregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Guruh ochilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupstudentmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='groupvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuklangan vaqt'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdtmexamresult',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentdtmexamresult',
            name='total_score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Umumiy ball'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='month',
            field=models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentabr', 'Sentabr'), ('Oktabr', 'Oktabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentquizresult',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studentquizresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuklangan vaqti'),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='category',
            field=models.CharField(choices=[('always_show', "Doimiy ko'rsatish (Banner)"), ('one_time', 'Tizimga 1-marta kirganda (Bir martalik)')], db_index=True, default='always_show', max_length=15, verbose_name='Turkum'),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='systemannouncement',
            name='target_role',
            field=models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('teacher', "Faqat o'qituvchilar"), ('student', "Faqat o'quvchilar")], db_index=True, default='all', max_length=15, verbose_name='Kimlar uchun'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
