# Generated by Django 5.2.6 on 2026-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_aianswer_is_correct_alter_aiquiz_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_token',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram Token'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('reception', 'Retseptsiya (Sub-admin)'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], db_index=True, max_length=15),
        ),
    ]
