# Generated by Django 5.2.6 on 2026-08-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_customuser_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_otp_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Telegram OTP Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram OTP Created At'),
        ),
    ]
