# Generated by Django 5.2.6 on 2026-08-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_customuser_telegram_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'group', 'date')},
        ),
    ]
