# Generated by Django 5.2.6 on 2026-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi"),
        ),
    ]
