# Generated by Django 5.2.6 on 2026-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_assignmentsubmission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subadmin_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Sub-admin huquqlari'),
        ),
    ]
