# Generated by Django 5.2.6 on 2026-08-04 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_customuser_subadmin_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Bloklangan URL')),
                ('reason', models.TextField(verbose_name='Bloklanish sababi')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloklangan vaqt')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol bloklash')),
            ],
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(db_index=True, max_length=255, verbose_name='Xatolik yuz bergan URL')),
                ('error_message', models.TextField(verbose_name='Xatolik xabari')),
                ('traceback', models.TextField(verbose_name='Traceback tafsiloti')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Hal etildi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal etilgan vaqt')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='Hal etgan shaxs')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
