# Generated by Django 5.2.6 on 2026-08-07 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_lockedpage_systemerrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='books/pdfs/', verbose_name='PDF Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuklangan vaqti')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.subject', verbose_name='Fan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklovchi')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
    ]
