# Generated by Django 5.2.6 on 2026-08-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Hamyon balansi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_of',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to=settings.AUTH_USER_MODEL, verbose_name='Farzandi'),
        ),
        migrations.AddField(
            model_name='group',
            name='salary_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Maosh tarifi (Foiz yoki Fix summa)'),
        ),
        migrations.AddField(
            model_name='group',
            name='salary_type',
            field=models.CharField(choices=[('percent', 'Foizli (Tushumdan)'), ('fixed', 'Darsbay (Ruxsat etilgan fixed)')], default='percent', max_length=15, verbose_name='Maosh turi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('reception', 'Retseptsiya (Sub-admin)'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('parent', 'Ota-ona')], db_index=True, max_length=15),
        ),
        migrations.CreateModel(
            name='TeacherSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'langan summa")),
                ('month', models.CharField(db_index=True, max_length=20, verbose_name='Qaysi oy uchun')),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="To'langan vaqti")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Guruh')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi maoshi to'lovi",
                'verbose_name_plural': "O'qituvchi maoshi to'lovlari",
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('transaction_type', models.CharField(choices=[('top_up', "Balansni to'ldirish"), ('payment', "Guruh uchun to'lov")], db_index=True, max_length=20, verbose_name='Turi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Hamyon tranzaksiyasi',
                'verbose_name_plural': 'Hamyon tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
