# Generated by Django 5.2.6 on 2026-08-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_customuser_parent_of_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parent_of',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to=settings.AUTH_USER_MODEL, verbose_name='Farzandi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('reception', 'Retseptsiya (Sub-admin)'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('parent', 'Ota-ona')], db_index=True, max_length=15),
        ),
    ]
