# Generated by Django 5.2.6 on 2026-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_customuser_parent_of_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent_of',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('reception', 'Retseptsiya (Sub-admin)'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], db_index=True, max_length=15),
        ),
    ]
