# Generated by Django 5.2.6 on 2026-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_customuser_parent_of_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Tizim', max_length=255, verbose_name='Brend nomi / Sayt nomi'),
        ),
    ]
