# Generated by Django 5.2.6 on 2026-09-02 05:40

import main.models
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_sitesetting_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to=main.models.assignment_upload_path, validators=[main.validators.validate_document_file], verbose_name='Topshiriq fayli'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='submissions/', validators=[main.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='books/pdfs/', validators=[main.validators.validate_pdf_file], verbose_name='PDF Fayl'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_profile_image_path, validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='dtmregistration',
            name='booklet_file',
            field=models.FileField(blank=True, null=True, upload_to='dtm_booklets/', validators=[main.validators.validate_pdf_file], verbose_name='Savollar kitobchasi PDF'),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/materials/', validators=[main.validators.validate_document_file], verbose_name='Dars materiali'),
        ),
        migrations.AlterField(
            model_name='groupvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.video_upload_path, validators=[main.validators.validate_video_file], verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='default/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='global/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(upload_to='subject_materials/', validators=[main.validators.validate_document_file], verbose_name='Fayl'),
        ),
    ]
