# Generated by Django 5.2.6 on 2026-09-02 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Qaysi oy uchun')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], db_index=True, max_length=20, verbose_name="To'lov tizimi")),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('paid', "To'landi"), ('cancelled', 'Bekor qilindi'), ('failed', 'Xatolik')], db_index=True, default='waiting', max_length=20, verbose_name='Holati')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Tranzaksiya ID (Tizim)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="To'langan vaqti")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "To'lov buyurtmasi",
                'verbose_name_plural': "To'lov buyurtmalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Click Tranzaksiya ID')),
                ('service_id', models.CharField(max_length=50, verbose_name='Xizmat ID')),
                ('click_paydoc_id', models.CharField(blank=True, max_length=255, null=True, verbose_name="Click To'lov Hujjati ID")),
                ('merchant_trans_id', models.CharField(db_index=True, max_length=255, verbose_name='Merchant Tranzaksiya ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('action', models.IntegerField(db_index=True, verbose_name='Amal kodi (0: Prepare, 1: Complete)')),
                ('error', models.IntegerField(default=0, verbose_name='Xatolik kodi')),
                ('status', models.CharField(db_index=True, default='waiting', max_length=50, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='main.paymentorder', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Click Tranzaksiyasi',
                'verbose_name_plural': 'Click Tranzaksiyalari',
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Payme Tranzaksiya ID')),
                ('time', models.BigIntegerField(db_index=True, verbose_name='Payme Vaqti (ms)')),
                ('amount', models.BigIntegerField(verbose_name='Summa (tiyinda)')),
                ('state', models.IntegerField(db_index=True, default=1, verbose_name='Holat kodi')),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor qilish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='main.paymentorder', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Payme Tranzaksiyasi',
                'verbose_name_plural': 'Payme Tranzaksiyalari',
            },
        ),
    ]
