# Generated by Django 5.2.6 on 2026-09-10 13:56

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_paymentorder_clicktransaction_paymetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='login_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='global/', validators=[main.validators.validate_image_file], verbose_name='Login fon rasmi'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='global/', validators=[main.validators.validate_image_file], verbose_name='Logotip'),
        ),
    ]
