# Generated by Django 5.2.6 on 2026-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_sitesetting_login_bg_image_alter_sitesetting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='eskiz_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eskiz.uz Email / Login'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='eskiz_from_name',
            field=models.CharField(default='4546', max_length=50, verbose_name='Eskiz Alfa-nom (Yuboruvchi)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='eskiz_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eskiz.uz Yashirin kalit / Parol'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='SMS xizmati faolmi'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sms_on_absence',
            field=models.BooleanField(default=True, verbose_name='Darsga kelmaganda SMS yuborish'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sms_on_payment',
            field=models.BooleanField(default=True, verbose_name="To'lov qabul qilinganda SMS yuborish"),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sms_on_register',
            field=models.BooleanField(default=True, verbose_name="Ro'yxatdan o'tganda login/parol yuborish"),
        ),
    ]
