# Generated by Django 5.2.6 on 2026-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_sitesetting_eskiz_email_sitesetting_eskiz_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Profil to'ldirilganmi"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Nizomga rozilik berilganmi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rozilik berilgan sana'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rozilik berilgan IP'),
        ),
    ]
