# Generated by Django 5.2.6 on 2026-09-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_customuser_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_bot_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Bot Username'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram Bot xizmati faolmi'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_on_absence',
            field=models.BooleanField(default=True, verbose_name='Darsga kelmaganda Telegram yuborish'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_on_payment',
            field=models.BooleanField(default=True, verbose_name="To'lov qabul qilinganda Telegram yuborish"),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_on_register',
            field=models.BooleanField(default=True, verbose_name="Ro'yxatdan o'tganda Telegram orqali login/parol yuborish"),
        ),
    ]
