# Generated by Django 5.2.6 on 2026-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_sitesetting_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Sharifi / Otasining ismi'),
        ),
    ]
