# Generated by Django 5.2.6 on 2026-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_customuser_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_clean', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Tozalangan telefon raqami')),
                ('chat_id', models.CharField(db_index=True, max_length=50, verbose_name='Telegram Chat ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Ism')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Familiya')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Username')),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Oxirgi OTP kod')),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP amal qilish muddati')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Telegram Bot Kontakti',
                'verbose_name_plural': 'Telegram Bot Kontaktlari',
            },
        ),
    ]
