# Generated by Django 5.2.6 on 2026-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_telegrambotcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemerrorlog',
            options={'verbose_name': 'Tizim xatolik jurnali', 'verbose_name_plural': 'Tizim xatolik jurnallari'},
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='exception_type',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Xatolik turi (Exception)'),
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='http_method',
            field=models.CharField(db_index=True, default='GET', max_length=10, verbose_name='HTTP Metod'),
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='IP Manzil'),
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='request_data',
            field=models.TextField(blank=True, null=True, verbose_name="So'rov parametrlari (JSON)"),
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Qurilma va Brauzer (User-Agent)'),
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='user_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Foydalanuvchi telefoni'),
        ),
        migrations.AddField(
            model_name='systemerrorlog',
            name='user_role',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Foydalanuvchi roli'),
        ),
    ]
