# Generated by Django 5.2.6 on 2026-09-14 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_systemerrorlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Netlify Dashboard', max_length=100, verbose_name='Kalit nomi')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='API Maxfiy Kaliti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi foydalanilgan vaqt')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol holatda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
            ],
            options={
                'verbose_name': 'Monitoring API Kaliti',
                'verbose_name_plural': 'Monitoring API Kalitlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
