# Generated by Django 5.2.6 on 2026-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_monitoringapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppaymentinfo',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov boshlanish sanasi"),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='cycle_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Oy tartib raqami'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov davri tugashi"),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov davri boshlanishi"),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='month',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
