# Generated by Django 5.2.6 on 2026-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_grouppaymentinfo_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Guruh yopilgan vaqti'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol / Ochiq guruh'),
        ),
    ]
