# Generated by Django 5.2.6 on 2026-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_group_closed_at_group_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arxivlangan vaqti'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arxivlangan'),
        ),
    ]
